import { readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const VAULT_ROOT = path.resolve(here, "src/synochi");
const OUT = path.resolve(here, "src/lib/synochi.generated.ts");

const FULL = ["SPINE", "IDENTITY", "PROTOCOLS", "Interaction Psychology", "Guidance Dynamics"];
const INDEX = ["MODELS", "MECHANISMS"];

function listMd(dir) {
  try {
    return readdirSync(dir).filter((f) => f.endsWith(".md")).map((f) => path.join(dir, f)).sort();
  } catch {
    return [];
  }
}

function clean(file) {
  return readFileSync(file, "utf8").replace(/\r\n/g, "\n").trim();
}

function fullSection(folder) {
  const dir = path.join(VAULT_ROOT, folder);
  const parts = [`## ${folder}`, ""];
  for (const f of listMd(dir)) {
    parts.push(`### ${path.basename(f, ".md")}`);
    parts.push(clean(f));
    parts.push("");
  }
  return parts.join("\n");
}

function indexSection(folder) {
  const dir = path.join(VAULT_ROOT, folder);
  const parts = [
    `## ${folder} — concept index (titles + first lines)`,
    "",
    "These are nodes you can reason about by name. Use the framework principles to expand them; never contradict the SPINE.",
    "",
  ];
  for (const f of listMd(dir)) {
    const title = path.basename(f, ".md");
    const body = clean(f);
    const stripped = body
      .split("\n")
      .filter((l) => !l.trim().startsWith("[[") && !l.trim().startsWith("#") && l.trim().length > 0)
      .slice(0, 3)
      .join(" ")
      .slice(0, 320);
    parts.push(`- **${title}** — ${stripped}`);
  }
  parts.push("");
  return parts.join("\n");
}

if (!statSync(VAULT_ROOT, { throwIfNoEntry: false })?.isDirectory()) {
  throw new Error(`Vault not found at ${VAULT_ROOT}`);
}

const sections = [
  "# SYNOCHI — Personal Operating System (full reference)",
  "",
  "SPINE laws are non-negotiable. IDENTITY describes how the self forms and holds. PROTOCOLS are actionable interventions. MECHANISMS and MODELS are referenced by title with short blurbs — reason from the framework when expanding them.",
  "",
];
for (const f of FULL) sections.push(fullSection(f));
for (const f of INDEX) sections.push(indexSection(f));

const vault = sections.join("\n");

const ts = `// AUTO-GENERATED by build-synochi.mjs. Do not edit by hand.\n` +
  `export const SYNOCHI_VAULT = ${JSON.stringify(vault)};\n`;

writeFileSync(OUT, ts);
console.log(`Synochi vault bundled → ${OUT} (${vault.length} chars)`);
