import { readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const VAULT_ROOT = path.resolve(here, "src/synochi");
const OUT = path.resolve(here, "src/lib/synochi.generated.ts");

const FULL = ["SPINE", "IDENTITY", "PROTOCOLS", "Interaction Psychology", "Guidance Dynamics"];
const DEEP = ["MODELS", "MECHANISMS"];

function listMd(dir) {
  try {
    return readdirSync(dir).filter((f) => f.endsWith(".md")).map((f) => path.join(dir, f)).sort();
  } catch {
    return [];
  }
}

function clean(file) {
  return readFileSync(file, "utf8").replace(/\r\n/g, "\n").trim();
}

function fullSection(folder) {
  const dir = path.join(VAULT_ROOT, folder);
  const parts = [`## ${folder}`, ""];
  for (const f of listMd(dir)) {
    parts.push(`### ${path.basename(f, ".md")}`);
    parts.push(clean(f));
    parts.push("");
  }
  return parts.join("\n");
}

function indexSection(folder) {
  const dir = path.join(VAULT_ROOT, folder);
  const parts = [
    `## ${folder} — concept index (titles + first lines)`,
    "",
    "These are nodes you can reason about by name. Use the framework principles to expand them; never contradict the SPINE. When you reference one, write it as [[Title]] — the retrieval layer will surface its full text into your context on the NEXT turn so you can quote it precisely.",
    "",
  ];
  for (const f of listMd(dir)) {
    const title = path.basename(f, ".md");
    const body = clean(f);
    const stripped = body
      .split("\n")
      .filter((l) => !l.trim().startsWith("[[") && !l.trim().startsWith("#") && l.trim().length > 0)
      .slice(0, 3)
      .join(" ")
      .slice(0, 320);
    parts.push(`- **${title}** — ${stripped}`);
  }
  parts.push("");
  return parts.join("\n");
}

function deepMap(folder) {
  const dir = path.join(VAULT_ROOT, folder);
  const out = {};
  for (const f of listMd(dir)) {
    const title = path.basename(f, ".md");
    out[title] = clean(f);
  }
  return out;
}

if (!statSync(VAULT_ROOT, { throwIfNoEntry: false })?.isDirectory()) {
  throw new Error(`Vault not found at ${VAULT_ROOT}`);
}

const sections = [
  "# SYNOCHI — Personal Operating System (full reference)",
  "",
  "SPINE laws are non-negotiable. IDENTITY describes how the self forms and holds. PROTOCOLS are actionable interventions. MECHANISMS and MODELS are indexed below by title with short blurbs — when one becomes relevant to the conversation, the system surfaces its FULL TEXT into the dynamic context block under '# Deep vault context pulled in for this turn'. Always prefer the deep-block wording over your own paraphrase when available.",
  "",
];
for (const f of FULL) sections.push(fullSection(f));
for (const f of DEEP) sections.push(indexSection(f));

const vault = sections.join("\n");

const deep = {};
for (const f of DEEP) deep[f] = deepMap(f);

const ts =
  `// AUTO-GENERATED by build-synochi.mjs. Do not edit by hand.\n` +
  `export const SYNOCHI_VAULT = ${JSON.stringify(vault)};\n` +
  `export const SYNOCHI_DEEP: Record<"MODELS" | "MECHANISMS", Record<string, string>> = ${JSON.stringify(deep)};\n`;

writeFileSync(OUT, ts);

const deepCount = Object.values(deep).reduce((s, m) => s + Object.keys(m).length, 0);
const deepChars = Object.values(deep).reduce(
  (s, m) => s + Object.values(m).reduce((s2, b) => s2 + b.length, 0),
  0,
);
console.log(
  `Synochi vault bundled → ${OUT}\n  cached vault: ${vault.length} chars\n  deep nodes:   ${deepCount} (${deepChars} chars total, retrieved per turn)`,
);
