uploads = []
outputs = []

[[generated]]
id = "MhtYRwK-AvX0h9SUt9Uvi"
uri = "file://artifacts/coach/public/spirit/wolf.png"
type = "image"
title = "wolf white line art"

[[generated]]
id = "lHdJmhETSxowzbl-Oo_dG"
uri = "file://artifacts/coach/public/spirit/falcon.png"
type = "image"
title = "falcon white line art"

[[generated]]
id = "-4jr37YBraQAVLO6ovUTe"
uri = "file://artifacts/coach/public/spirit/bear.png"
type = "image"
title = "bear white line art"

[[generated]]
id = "yfqe-A5MkI5nhodE_VsYr"
uri = "file://artifacts/coach/public/spirit/cobra.png"
type = "image"
title = "cobra white line art"

[[generated]]
id = "v-wCjCuIq2PeMzMNhUW-A"
uri = "file://artifacts/coach/public/spirit/panther.png"
type = "image"
title = "panther white line art"

[[generated]]
id = "8NvUcGKCGYYWnUTfqL6hz"
uri = "file://artifacts/coach/public/spirit/ox.png"
type = "image"
title = "ox white line art"

[[generated]]
id = "nOuDajAAPMhv2WfduF3Fl"
uri = "file://artifacts/coach/public/spirit/shark.png"
type = "image"
title = "shark white line art"

[[generated]]
id = "EOY04x6XbBZkHeO77dXeA"
uri = "file://artifacts/coach/public/spirit/eagle.png"
type = "image"
title = "eagle white line art"

[[generated]]
id = "hN0m2lgPA4mXQLi-A4eMk"
uri = "file://artifacts/coach/public/spirit/mantis.png"
type = "image"
title = "mantis white line art"

[[generated]]
id = "WoR1yJiwpB65QVN3ZtDAs"
uri = "file://artifacts/coach/public/spirit/ram.png"
type = "image"
title = "ram white line art"

[[generated]]
id = "PRsSdEoNCfSR0GFgcflLa"
uri = "file://artifacts/frame-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"
